In [1]:
import numpy as np
ar=np.zeros(10)
ar[4]=1
ar

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [2]:
ar=np.random.randint(10,15,15)
ar.shape=5,3
ar


array([[13, 13, 12],
       [10, 13, 10],
       [13, 12, 11],
       [13, 10, 12],
       [13, 14, 13]])

In [3]:
ar.shape,ar.size,ar.ndim,ar.dtype,ar.itemsize

((5, 3), 15, 2, dtype('int32'), 4)

In [4]:
ar.shape=3,5
ar

array([[13, 13, 12, 10, 13],
       [10, 13, 12, 11, 13],
       [10, 12, 13, 14, 13]])

In [5]:
ar=ar.ravel()
ar2=ar
ar2[1:-1]

array([13, 12, 10, 13, 10, 13, 12, 11, 13, 10, 12, 13, 14])

In [6]:
ar=ar.flatten()
ar2=ar
ar2[1:-1]

array([13, 12, 10, 13, 10, 13, 12, 11, 13, 10, 12, 13, 14])

In [7]:
ar2[1]=100
ar2

array([ 13, 100,  12,  10,  13,  10,  13,  12,  11,  13,  10,  12,  13,
        14,  13])

In [8]:
ar

array([ 13, 100,  12,  10,  13,  10,  13,  12,  11,  13,  10,  12,  13,
        14,  13])

In [9]:
ar[-1::-1]

array([ 13,  14,  13,  12,  10,  13,  11,  12,  13,  10,  13,  10,  12,
       100,  13])

In [13]:
ar=np.random.random([3,5])
print(ar)
ar[[1,2],[0,1]]

[[0.16000941 0.93007271 0.39304265 0.29362922 0.39674974]
 [0.06419078 0.1347878  0.36219531 0.12331878 0.05255706]
 [0.9967689  0.51729308 0.60836842 0.89442439 0.24224764]]


array([0.06419078, 0.51729308])

In [14]:
a=np.arange(0,9)
b=np. arange(10,30,2)
print (a,b,sep='\n')
a.resize(3,3)
b.resize(3,3)
print(a, b,sep='\n')
np.hstack([a,b])

[0 1 2 3 4 5 6 7 8]
[10 12 14 16 18 20 22 24 26 28]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 12 14]
 [16 18 20]
 [22 24 26]]


array([[ 0,  1,  2, 10, 12, 14],
       [ 3,  4,  5, 16, 18, 20],
       [ 6,  7,  8, 22, 24, 26]])

In [15]:
np.vstack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [16]:
names=np.array(['mary','ton','ketty','nike','lily','rose'])
grades=np. array([80,95,50,70,65,86])
name=input("请输入你的姓名以查询你的考试成绩:")
names==name
print(name,"同学的考试成绩为:",*grades[names==name])

请输入你的姓名以查询你的考试成绩:rose
rose 同学的考试成绩为: 86


In [18]:
print(*names)
print(names)

mary ton ketty nike lily rose
['mary' 'ton' 'ketty' 'nike' 'lily' 'rose']


In [19]:
np.max(grades),np.min(grades),np.mean(grades),np.median(grades)

(95, 50, 74.33333333333333, 75.0)

In [20]:
level=np.where(grades>=60,"通过","不通过")
level

array(['通过', '通过', '不通过', '通过', '通过', '通过'], dtype='<U3')

In [21]:
x=np.load('C:/Users/52335/Desktop/00/学习/python/其他文件/isrs.npy',allow_pickle=True)

In [22]:
print(x)
print(x.ndim,x.size,x.shape)

[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 0.3 'Iris-setosa']
 [5.1 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa']
 [5.1 3.7 1.5 0.4 'Iris-setosa']
 [4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.1 3.3 1.7 0.5 'Iris-setosa']
 [4.8 3.4 1.9 0.2 'Iris-setosa']
 [5.0 3.0 1.6 0.2 'Iris-setosa']
 [5.0 3.4 1.6 0.4 'Iris-setosa']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.6 0.2 'Iris-setosa']
 [4.8 3.1 

In [7]:
print( np.unique( x[:,-1] ) )

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [23]:
print( np.unique( x[:,-1] ) )

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [24]:
data,flowers=x[:,:-1],x[:,-1]
print(data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [25]:
np.max(data,axis=0)

array([7.9, 4.4, 6.9, 2.5], dtype=object)

In [26]:
print('Setosa',np.sum(flowers=='Iris-setosa'))
print('Versicolor',np.sum(flowers=='Iris-versicolor'))
print('Virginica',np.sum(flowers=='Iris-virginica') )

Setosa 50
Versicolor 50
Virginica 50


In [27]:
for i in np.unique(flowers):
    print(i)
    datai=data[flowers==i]
    print("{:^7s}".format('max'),np.max(datai,axis=0))
    print("{:^7s}".format('min'),np.min(datai,axis=0))
    print("{:^7s}".format('median'),np.median(datai,axis=0))

Iris-setosa
  max   [5.8 4.4 1.9 0.6]
  min   [4.3 2.3 1.0 0.1]
median  [5.0 3.4 1.5 0.2]
Iris-versicolor
  max   [7.0 3.4 5.1 1.8]
  min   [4.9 2.0 3.0 1.0]
median  [5.9 2.8 4.35 1.3]
Iris-virginica
  max   [7.9 3.8 6.9 2.5]
  min   [4.9 2.2 4.5 1.4]
median  [6.5 3.0 5.55 2.0]


In [28]:
ar=np.load('C:/Users/52335/Desktop/00/学习/python/其他文件/popu.npy',allow_pickle=True)
ar

array([['安徼', 59500468, 61027171],
       ['北京', 19612368, 21893095],
       ['福建', 36894217, 41540086],
       ['甘肃', 25575263, 25019831],
       ['广东', 104320459, 126012510],
       ['广西', 46023761, 50126804],
       ['贵州', 34748556, 38562148],
       ['海南', 8671485, 10081232],
       ['河北', 71854210, 74610235],
       ['河南', 94029939, 99365519],
       ['黑龙江', 38313991, 31350088],
       ['湖北', 57237727, 57752557],
       ['湖南', 65700762, 66444864],
       ['吉林', 27452815, 24073453],
       ['江苏', 78660941, 84748016],
       ['江西', 44567797, 45188635],
       ['辽宁', 43746323, 42591407],
       ['内蒙古', 24706291, 24049155],
       ['宁夏', 6301350, 7202654],
       ['青海', 5626723, 5923957],
       ['山东', 95792719, 101527453],
       ['山西', 35712101, 34915616],
       ['陕西', 37327379, 39528999],
       ['上海', 23019196, 24870895],
       ['四川', 80417528, 83674366],
       ['天津', 12938693, 13866009],
       ['西藏', 3002165, 3648100],
       ['新疆', 21815815, 25852345],
       ['云南', 45966766

In [29]:
ar[:,1:].sum(axis=0)/100000000

array([13.32810869, 14.09278224], dtype=object)

In [18]:
for i in sorted(ar,key=lambda x:x[1],reverse=True):
    print(i)

['广东' 104320459 126012510]
['山东' 95792719 101527453]
['河南' 94029939 99365519]
['四川' 80417528 83674366]
['江苏' 78660941 84748016]
['河北' 71854210 74610235]
['湖南' 65700762 66444864]
['安徼' 59500468 61027171]
['湖北' 57237727 57752557]
['浙江' 54426891 64567588]
['广西' 46023761 50126804]
['云南' 45966766 47209277]
['江西' 44567797 45188635]
['辽宁' 43746323 42591407]
['黑龙江' 38313991 31350088]
['陕西' 37327379 39528999]
['福建' 36894217 41540086]
['山西' 35712101 34915616]
['贵州' 34748556 38562148]
['重庆' 28846170 32054159]
['吉林' 27452815 24073453]
['甘肃' 25575263 25019831]
['内蒙古' 24706291 24049155]
['上海' 23019196 24870895]
['新疆' 21815815 25852345]
['北京' 19612368 21893095]
['天津' 12938693 13866009]
['海南' 8671485 10081232]
['宁夏' 6301350 7202654]
['青海' 5626723 5923957]
['西藏' 3002165 3648100]


In [20]:
for i in sorted(ar,key=lambda x:x[2],reverse=True):
    print(i)


['广东' 104320459 126012510]
['山东' 95792719 101527453]
['河南' 94029939 99365519]
['江苏' 78660941 84748016]
['四川' 80417528 83674366]
['河北' 71854210 74610235]
['湖南' 65700762 66444864]
['浙江' 54426891 64567588]
['安徼' 59500468 61027171]
['湖北' 57237727 57752557]
['广西' 46023761 50126804]
['云南' 45966766 47209277]
['江西' 44567797 45188635]
['辽宁' 43746323 42591407]
['福建' 36894217 41540086]
['陕西' 37327379 39528999]
['贵州' 34748556 38562148]
['山西' 35712101 34915616]
['重庆' 28846170 32054159]
['黑龙江' 38313991 31350088]
['新疆' 21815815 25852345]
['甘肃' 25575263 25019831]
['上海' 23019196 24870895]
['吉林' 27452815 24073453]
['内蒙古' 24706291 24049155]
['北京' 19612368 21893095]
['天津' 12938693 13866009]
['海南' 8671485 10081232]
['宁夏' 6301350 7202654]
['青海' 5626723 5923957]
['西藏' 3002165 3648100]


In [30]:
gt=(ar[:,2]-ar[:,1])/10000
gt

array([152.6703, 228.0727, 464.5869, -55.5432, 2169.2051, 410.3043,
       381.3592, 140.9747, 275.6025, 533.558, -696.3903, 51.483, 74.4102,
       -337.9362, 608.7075, 62.0838, -115.4916, -65.7136, 90.1304,
       29.7234, 573.4734, -79.6485, 220.162, 185.1699, 325.6838, 92.7316,
       64.5935, 403.653, 124.2511, 1014.0697, 320.7989], dtype=object)

In [31]:
ar1 = gt.reshape(31,1)
ar1

array([[152.6703],
       [228.0727],
       [464.5869],
       [-55.5432],
       [2169.2051],
       [410.3043],
       [381.3592],
       [140.9747],
       [275.6025],
       [533.558],
       [-696.3903],
       [51.483],
       [74.4102],
       [-337.9362],
       [608.7075],
       [62.0838],
       [-115.4916],
       [-65.7136],
       [90.1304],
       [29.7234],
       [573.4734],
       [-79.6485],
       [220.162],
       [185.1699],
       [325.6838],
       [92.7316],
       [64.5935],
       [403.653],
       [124.2511],
       [1014.0697],
       [320.7989]], dtype=object)

In [32]:
data=np.insert(ar,obj=3,values=(ar[:,2]-ar[:,1])/10000,axis=1)
data=np.insert(data,obj=4,values=data[:,3]/data[:,1]*1000000,axis=1)
data

array([['安徼', 59500468, 61027171, 152.6703, 2.565867213010829],
       ['北京', 19612368, 21893095, 228.0727, 11.629024093368022],
       ['福建', 36894217, 41540086, 464.5869, 12.592404386844692],
       ['甘肃', 25575263, 25019831, -55.5432, -2.171754792902814],
       ['广东', 104320459, 126012510, 2169.2051, 20.7936690539293],
       ['广西', 46023761, 50126804, 410.3043, 8.915053682813971],
       ['贵州', 34748556, 38562148, 381.3592, 10.974821514885395],
       ['海南', 8671485, 10081232, 140.9747, 16.25727311988662],
       ['河北', 71854210, 74610235, 275.6025, 3.8355790147856337],
       ['河南', 94029939, 99365519, 533.558, 5.674341658352028],
       ['黑龙江', 38313991, 31350088, -696.3903, -18.17587470853663],
       ['湖北', 57237727, 57752557, 51.483, 0.8994591976023086],
       ['湖南', 65700762, 66444864, 74.4102, 1.1325622068127612],
       ['吉林', 27452815, 24073453, -337.9362, -12.309710315681652],
       ['江苏', 78660941, 84748016, 608.7075, 7.738370432156411],
       ['江西', 44567797, 451886

In [33]:
data=np.insert(data,obj=4,values=data[:,3]/data[:,1]*1000000,axis=1)
data

array([['安徼', 59500468, 61027171, 152.6703, 2.565867213010829,
        2.565867213010829],
       ['北京', 19612368, 21893095, 228.0727, 11.629024093368022,
        11.629024093368022],
       ['福建', 36894217, 41540086, 464.5869, 12.592404386844692,
        12.592404386844692],
       ['甘肃', 25575263, 25019831, -55.5432, -2.171754792902814,
        -2.171754792902814],
       ['广东', 104320459, 126012510, 2169.2051, 20.7936690539293,
        20.7936690539293],
       ['广西', 46023761, 50126804, 410.3043, 8.915053682813971,
        8.915053682813971],
       ['贵州', 34748556, 38562148, 381.3592, 10.974821514885395,
        10.974821514885395],
       ['海南', 8671485, 10081232, 140.9747, 16.25727311988662,
        16.25727311988662],
       ['河北', 71854210, 74610235, 275.6025, 3.8355790147856337,
        3.8355790147856337],
       ['河南', 94029939, 99365519, 533.558, 5.674341658352028,
        5.674341658352028],
       ['黑龙江', 38313991, 31350088, -696.3903, -18.17587470853663,
        -18.175

In [34]:
data[ data[:,3]>0,0]

array(['安徼', '北京', '福建', '广东', '广西', '贵州', '海南', '河北', '河南', '湖北', '湖南',
       '江苏', '江西', '宁夏', '青海', '山东', '陕西', '上海', '四川', '天津', '西藏', '新疆',
       '云南', '浙江', '重庆'], dtype=object)

In [35]:
x=sorted(data,key=lambda x:x[3],reverse=True)
for i in x:
    print(i[0],end=',')

广东,浙江,江苏,山东,河南,福建,广西,新疆,贵州,四川,重庆,河北,北京,陕西,上海,安徼,海南,云南,天津,宁夏,湖南,西藏,江西,湖北,青海,甘肃,内蒙古,山西,辽宁,吉林,黑龙江,

In [37]:
import pandas as pd 
from pyecharts.charts import Map
from pyecharts import options as opts 
data=np.load(r'popu.npy',allow_pickle=True)
data=np.insert(data,obj=3,values=(data[:,2]-data[:,1])/10000,axis=1)#axis=表示插入列
data= np.delete(data,0,axis=1)
b=np.array(['安徼省', '北京市', '福建省', '广东省', '广西壮族自治区', '贵州省', '海南省', '河北省', '河南', '湖北', '湖南',
       '江苏省', '江西省', '宁夏回族自治区', '青海省', '山东省', '陕西省', '上海市', '四川省, '天津', '西藏', '新疆',
       '云南省', '浙江省', '重庆市'])
data= np.insert(data,0,values=b,axis=1)
data=data[:,[0,3]]
_max =600
_min =-600
map_ = Map()
map_.add("", data, maptype="china", zoom=1)
map_.set_global_opts(
    title_opts=opts.TitleOpts(title="各省人口流量变化总体情况",
                              subtitle="数据来源：国家统计局",
                              pos_right="center",
                              pos_top="5%"),                   
    visualmap_opts=opts.VisualMapOpts(max_=_max,
                                      min_=_min
                                     )
    )
map_.render("C:/Users/52335/Desktop/各省人口流量变化总体情况.html")


'C:\\Users\\52335\\Desktop\\各省人口流量变化总体情况.html'